[mgr]
prepend_keymap = [
	{ on = "<C-h>", run = 'shell -- theylix -h "$@"', desc = "Open in Helix with horizontal split" },
	{ on = "<C-v>", run = 'shell -- theylix -v "$@"', desc = "Open in Helix with vertical split" },
	{ on = [ "m" ], run = "plugin bookmarks save", desc = "Save current position as a bookmark" },
	{ on = [ "'" ], run = "plugin bookmarks jump", desc = "Jump to a bookmark" },
	{ on = [ "b", "d" ], run = "plugin bookmarks delete", desc = "Delete a bookmark" },
	{ on = [ "b", "D" ], run = "plugin bookmarks delete_all", desc = "Delete all bookmarks"},
]
