{
  imports = [
    ./options.nix
    ./mcp.nix
    ./rtk.nix
    ./pi.nix
    ./nix-profile-cleanup.nix
    ./codex
    ./cursor
    ./kiro.nix
    ./codeium.nix
    ./cc-switch.nix
    ./herdr
    ./cliproxyapi.nix
    ./collie.nix
    ./orca.nix
    ./cursor-to-openai.nix
    ./dsh.nix
  ];
}
