(package! org-analyzer)
(package! embark)
(package! dashboard)
(package! direnv)
(package! org-modern)
(package! org-super-agenda)
(package! emacsql)
(package! org-roam-ui)
(package! org-transclusion)
(package! org-download)
(package! org-web-tools :recipe (:host github :repo "alphapapa/org-web-tools"))

(package! org-yt :recipe (:local-repo "package"))
;; (package! mu4e :recipe (:local-repo "package/mu4e"))
(package! mu4e-alert :recipe (:host github :repo "iqbalansari/mu4e-alert"))

(package! toc-org)
(package! lister)
(package! all-the-icons-ibuffer)
(package! all-the-icons-dired)
(package! all-the-icons-completion)
(package! ox-reveal)
(package! magit-todos)
(package! hledger-mode)
(package! rainbow-mode)
(package! crdt)
(package! ess)
(package! openwith)
(package! ob-mermaid)
(package! focus)
(package! olivetti)
(package! async)
(package! centered-cursor-mode)
(package! elfeed)
(package! elfeed-protocol)
(package! docker-tramp :disable t)
(package! org-ql)
(package! persist)
(package! sudo-edit)
(package! solaire-mode :disable t)
(package! el-patch)
(package! devdocs)
